version: "3"
services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: work_planning_service
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: yarn start
    volumes:
      - .:/src/app
      - /src/app/node_modules
    ports:
      - "3600:3600"
    depends_on:
      - db
volumes:
  db-data:
